provider:
  name: faas
  gateway: http://localhost:8080

functions:
  issue-bot:
    lang: python
    handler: ./bot-handler
    image: alexellis2/issue-bot
    environment:
      write_debug: true
      auth_token: <auth_token_value>
      repo: <github_username>/bot-tester
      positive_threshold: 0.6
      gateway_hostname: "gateway"